apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend
  namespace: acmebookstore-local-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
        - name: store-frontend-container
          image: store-frontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m" # 1000m = 1 CPU core
              memory: "128Mi" # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: "50m"  # 0.75 CPU cores
              memory: "64Mi"  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
          env:
            - name: VUE_APP_BASE_URL
              value: "http://localhost:8082"
