apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: bookapp-local-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "100m" # 1000m = 1 CPU core
              memory: "128Mi" # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: "50m"  # 0.75 CPU cores
              memory: "64Mi"  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes 
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/library"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dbusername"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dbpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: bookapp-local-cicd
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080