apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-change-management
  namespace: bookapp-local-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-change-management
  template:
    metadata:
      labels:
        app: db-change-management
    spec:
      containers:
        - name: db-change-management
          image: db-change-management:latest  # Replace with the actual image name and tag
          ports:
            - containerPort: 5432  # Adjust the port if needed
          resources:
            limits:
              cpu: "100m" # 1000m = 1 CPU core
              memory: "128Mi" # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: "50m"  # 0.75 CPU cores
              memory: "64Mi"  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes  
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: "jdbc:postgresql://db:5432/library?user=dbusername&password=dbpassword"
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: "changelog-master.xml"
            - name: LIQUIBASE_LOG_LEVEL
              value: "INFO"
            - name: LIQUIBASE_SEARCH_PATH
              value: "changelog/,changelog/schema/,changelog/schema/tables/, changelog/seed/"