# Use the official pgAdmin image as the base
FROM dpage/pgadmin4

# Set environment variables for default email and password
# ENV PGADMIN_DEFAULT_EMAIL=email@example.com
# ENV PGADMIN_DEFAULT_PASSWORD=pgadminpassword

# Expose port 80 (pgAdmin runs on this port by default)
EXPOSE 80